version: 2
jobs:
  build_elixir:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          echo hello-world
      - run:
          name: Elixir イメージのビルド
          command: docker build -t circleci/elixir:example .